name: Server
on:
  push:
  pull_request:
  release:
    types: [published]

jobs:
  build:
    name: Server build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.15'
      - name: Get current Go version
        run: go version
      - name: Get Go dependencies
        working-directory: ./server/
        run: go mod download
      - name: Install Protoc
        uses: arduino/setup-protoc@v1
      - name: Install Go protoc
        run: go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
      - name: Generate protobuf
        run: protoc --proto_path=./messages --go_out=./ messages/*.proto
      - name: Build app
        working-directory: ./server/
        run: go build -o ptrun-server ./cmd/ptrun-server/main.go
  docker:
    name: Docker build
    if: ${{ github.event_name == 'create' }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get Docker version
        run: docker --version
      - name: Docker Login
        uses: docker/login-action@v1
        with:
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
          registry: "ghcr.io"
      - name: Get the tag
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          file: "./docker/Dockerfile.server"
          tags: ghcr.io/${{ github.repository }}/server:${{ steps.get_version.outputs.VERSION }}
          push: true
