name: Server
on:
  push:
  pull_request:

jobs:
  build:
    name: Server build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.13.1' # The Go version to download (if necessary) and use.
      - name: Get current Go version
        run: go version
      - name: Get Go dependencies
        working-directory: ./server/
        run: go mod download
      - name: Build app
        working-directory: ./server/
        run: go build -o ptrun-server ./cmd/ptrun-server/main.go
  docker:
    name: Docker build
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get Docker version
        run: docker --version
      - name: Docker Login
        uses: docker/login-action@v1
        with:
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
          registry: "ghcr.io"
      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          file: "./docker/Dockerfile.server"
          tags: ghcr.io/mytja-archive/ptrun/server:0.0.1
          push: false
